# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Clean project
      run: msbuild -t:Clean
    - name: Print Packages
      run: dir
    - name: Restore Packages
      run: msbuild /t:Restore
#      run: msbuild /t:Restore FileManagerDB\FileManagerDB.csproj && msbuild /t:Restore FileDBManagerTest\FileDBManagerTest.csproj && msbuild /t:Restore SymLinkMaker\SymLinkMaker.csproj && msbuild /t:Restore SymLinkMakerTest\SymLinkMakerTest.csproj && msbuild /t:Restore FileOrganizerCore\FileOrganizerCore.csproj && msbuild /t:Restore FileOrganizerCoreTest\FileOrganizerCoreTest.csproj && msbuild /t:Restore FileOrganizerUI\FileOrganizerUI.csproj
    - name: Build
      run: msbuild
    - name: FileDBManager Tests
      run: msbuild FileDBManagerTest\FileDBManagerTest.csproj -t:Test
    - name: SymLinkMaker Tests
      run: msbuild SymLinkMakerTest\SymLinkMakerTest.csproj -t:Test
    - name: FileOrganizerCore Tests
      run: msbuild FileOrganizerCoreTest\FileOrganizerCoreTest.csproj -t:Test
